version: "3"

services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management